services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  transformation-service:
    build:
      context: .
      dockerfile: transformation_service/Dockerfile
    restart: always
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./storage:/src/storage
  loader-service:
    build:
      context: .
      dockerfile: loader_service/Dockerfile
    environment:
      PORT: 8001
    ports:
      - '8001:8001'
    depends_on:
      - postgres
    volumes:
      - ./storage:/src/storage
