info:
  raw_data: storage/raw_data/amzf
  modelled_data: storage/mmodelled_data/amzf

transformation_config:
  new_schema:
    # TODO: add require field (ex: id)
    gender:
      source_name: gender
    first_name:
      source_name: name
      transform_method:
        - name: get_val_from_dict_by_key
          param: 
            - first
    last_name:
      source_name: name
      transform_method:
        - name: get_val_from_dict_by_key
          param:
            - last
    dob:
      source_name: dob
      transform_method:
        - name: get_val_from_dict_by_key
          param:
            - date
    country_code:
      source_name: nat
    app_name:
      transform_method:
        - name: add_column_constant
          param:
            - amzf
    id:
      source_name: whole
      transform_method:
        - name: create_primary_key_base_on_col
          param:
            - gender
            - first_name
            - last_name
            - dob
            - country_code

loader_config:
  schema_info:
    table: users
    pk: id
    columns:
      - id
      - first_name
      - last_name
      - gender
      - dob
      - country_code
      - app_name
  # Further thing to do before load for example join
  join: TODO
