info:
  raw_data: storage/raw_data/wm
  modelled_data: storage/modelled_data/wm

transformation_config:
  new_schema:
    # TODO: add require field (ex: id)
    gender:
      source_name: gender
    first_name:
      source_name: first
    last_name:
      source_name: last
    dob:
      source_name: dob
    country_code:
      source_name: ip_address 
      transform_method:
        - name: get_country_code
    app_name:
      transform_method:
        - name: add_column_constant
          param:
            - wm
    id:
      source_name: whole
      transform_method:
        - name: create_primary_key_base_on_col
          param:
            - gender
            - first_name
            - last_name
            - dob
            - country_code

loader_config:
  schema_info:
    table: users
    pk: id
    columns:
      - id
      - first_name
      - last_name
      - gender
      - dob
      - country_code
      - app_name
  # Further thing to do before load for example join
  join: TODO
